theme: jekyll-theme-minimal
title: ğŸğŸ’»ğŸ“
description: Andrei Torres' Digital Academic CV
logo: /assets/img/photo-andrei-profile-640px.jpg
cloudflare_web_analytics: 9babed5686084acea41895c0936a2ebb
